server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: marcasMS
          uri: lb://marcasMS:8091
          predicates:
            - Path=/autofix/marcas/**
        - id: reparacionesMS
          uri: lb://reparacionesMS:8092
          predicates:
            - Path=//autofix/reparaciones/**
        - id: vehiculosMS
          uri: lb://vehiculosMS:8093
          predicates:
            - Path=//autofix/vehiculos/**
        - id: citasMS
          uri: lb://citasMS:8094
          predicates:
            - Path=//autofix/citas/**